services:
  SwatShare:
    image: registry.sccs.swarthmore.edu/cs77-s25/SwatShare/SwatShare:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
    #env_file:
    #  - .env
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.SwatShare.entrypoints=https"
        - "traefik.http.routers.SwatShare.rule=Host(`SwatShare.sccs.swarthmore.edu`)"
        - "traefik.http.routers.SwatShare.tls=true"
        - "traefik.http.routers.SwatShare.tls.certresolver=letsEncrypt"
        - "traefik.http.services.SwatShare.loadbalancer.server.port=5000"
    networks:
      - internal
      - traefik

networks:
  internal:

  traefik:
    external: true
